safe:        false
port:        4000
baseurl:     /
url:         http://localhost:4000

source:      ./src
destination: ./dist
plugins_dir: ./_plugins
keep_files:  [media]

future:      true
lsi:         false
highlighter: false
markdown:    kramdown
permalink:   date

imagepath:    /media/img
alphabet:     [a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z]

rdiscount:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style